site_name: 病毒吧进吧导航（长期更新）
site_url: https://test.aaqwq.me
repo_url: https://github.com/weasUXL/bdb_docs
copyright: Copyright © 2025

theme:
  name: material
  language: zh
  favicon: images/favicon.ico
  logo: images/logo.png

  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式

  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - content.zoom

plugins:
  - glightbox
  - search
  - encryptcontent:
      title_prefix: '[已加密]'
      summary: '按照首页提示阅读完相关章节获取密码！'
      placeholder: '请输入密码'
      decryption_failure_message: ' 不要乱输密码(* ￣︿￣))'
      encryption_info_message: "阅读完毕网页会自动弹出窗口显示密码"
      password_button: true  
      password_button_text: '我要加群'

extra:
  generator: false
  
extra_javascript:
  - assets/js/viewqun.js  

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      title: 目录
